### ISSUE TITLE
1.16.1 server crashes

### ISSUE THREAD

**Issue by augustresende** [gigaherz/signbutton#2]
`
←[m←[1;31m[17:36:19] [main/FATAL] [minecraft/Main]: Failed to start the minecraft server
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
        Sign Button (signbutton) has failed to load correctly
§7Attempted to load class net/minecraft/client/renderer/texture/AtlasTexture for invalid dist DEDICATED_SERVER,
        Fake Blocks (fakeblocks) has failed to load correctly
§7java.lang.NoSuchMethodError: de.maxhenkel.fakeblocks.Main.clientSetup(Lnet/minecraftforge/fml/event/lifecycle/FMLClientSetupEvent;)V
]
        at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:218) ~[?:?] {re:classloading}
        at net.minecraftforge.fml.ModLoader.gatherAndInitializeMods(ModLoader.java:200) ~[?:?] {re:classloading}
        at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:49) ~[?:?] {re:classloading}
        at net.minecraft.server.Main.main(Main.java:94) ~[?:?] {re:classloading}
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_251] {}
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251] {}
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_251] {}
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_251] {}
        at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[forge-1.16.1-32.0.63.jar:32.0] {}
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.1.0.jar:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.1.0.jar:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.1.0.jar:?] {}
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.1.0.jar:?] {}
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.1.0.jar:?] {}
        at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63) [forge-1.16.1-32.0.63.jar:?] {}
        at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60) [forge-1.16.1-32.0.63.jar:?] {}
        at net.minecraftforge.server.ServerMain.main(ServerMain.java:57) [forge-1.16.1-32.0.63.jar:?] {}

`

**Comment by gigaherz** [comment]
Ah, thanks for reporting! I wonder why this didn't crash on 1.15.... or maybe it did... 🤔

**Comment by gigaherz** [comment]
v2.1.1 should fix this.
